@echo off
echo Stopping any running Node.js processes...
taskkill /F /IM node.exe >nul 2>&1
echo Starting backend server...
start "" "%COMSPEC%" /c "cd /d %~dp0backend && npm run dev"
echo Backend server is starting...
